// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6RFauCjjuzrKNydOVrvsaAVfyj1pMwf4',
    appId: '1:308573873242:web:a9ad37ec6a16e3e8f86463',
    messagingSenderId: '308573873242',
    projectId: 'image-gallery-app-46174',
    authDomain: 'image-gallery-app-46174.firebaseapp.com',
    storageBucket: 'image-gallery-app-46174.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwRTyDYhRJ8MDe__QHoMG1PBwWiWJXFtk',
    appId: '1:308573873242:android:d3aea0210ec2a500f86463',
    messagingSenderId: '308573873242',
    projectId: 'image-gallery-app-46174',
    storageBucket: 'image-gallery-app-46174.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6BAl8sppPUvdnaAQ1ED4AHwtW8BG298',
    appId: '1:308573873242:ios:2144302e74a4dac8f86463',
    messagingSenderId: '308573873242',
    projectId: 'image-gallery-app-46174',
    storageBucket: 'image-gallery-app-46174.appspot.com',
    iosClientId: '308573873242-1e5v45c1kd5oqbebpn3ife4qvk9fmqu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageGallary',
  );
}
