name: Flutter analyze and check code format
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  ci_flutter:
    name: enforce formatting and linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.7.0
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: run code gen
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze files
        run: flutter analyze lib

      - name: Check format files exclude generate files
        run: find lib -name "*.dart" ! -name "*.g.dart" ! -name "*.gr.dart" ! -name "*.freezed.dart" ! -path '*/generated/*'  | tr '\n' ' ' | xargs dart format -l "80" --set-exit-if-changed
